clear;
clear all;
load kuai3tezheng;
load kuai4tezheng;
load kuai5tezheng;
load kuai6tezheng;
load kuai7tezheng;
load kuai8tezheng;
load kuai3leibiao;
load kuai4leibiao;
load kuai5leibiao;
load kuai6leibiao;
load kuai7leibiao;
load kuai8leibiao;
train_tezheng=[kuai3tezheng;kuai4tezheng;kuai5tezheng;kuai6tezheng];
train_leibiao=[kuai3leibiao;kuai4leibiao;kuai5leibiao;kuai6leibiao];
test_tezheng=[kuai7tezheng;kuai8tezheng];
test_leibiao=[kuai7leibiao;kuai8leibiao];
N1=625;N2=625;N3=626;
rand('state',16917921);
b1=2*rand(size(train_tezheng,2)+1,N1)-1;
b2=2*rand(N1+1,N2)-1;
b3=orth(2*rand(N2+1,N3)'-1)';
C = 2^-30 ; s = 0.6;
[TrainingAccuracy,TestingAccuracy,Training_time,Testing_time] = DSWAN(train_tezheng,train_leibiao,test_tezheng,test_leibiao,b1,b2,b3,s,C);
